name: Sync to Personal Repo

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Org Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Personal Repo
        env:
          MY_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          # Use the variable in the URL
          git remote add personal "https://x-access-token:$MY_TOKEN@github.com/kingigbozuruike/dgclive.git"
          git push personal main --force
